version: '2'

services:
  vpn:
    build: '.'

    ports:
      - "8111:8111"

    volumes:
      - "./data:/data/teamcity_server/datadir"
      - "./logs:/opt/teamcity/logs"

    restart: always
    container_name: teamcity_server